name: Bulid My Application
on: push

jobs:
   build:
    name: Build our App
    runs-on: ubuntu-latest
    steps:
       - name: Pull Code
         uses: actions/checkout@v3
       - name: Print Current Directory
         run: pwd
       - name: List Files in Directory
         run: ls
       - name: TrickingLibrary.Api
         run: ls TrickingLibrary.Api/
       - name: Check Dotnet Cli
         run: dotnet build
       - name: Check Dotnet Cli
         run: ls TrickingLibrary.Api/ -R
       - name: Check NPM Cli
         run: npm -v

